Process "/home/david/Projects/rst2pdf_py2/bin/rst2pdf" started on Fri Jun  5 12:30:15 2015

        /home/david/Projects/rst2pdf_py2/bin/rst2pdf --date-invariant
        -v test_issue_312_2.txt -o
        /home/david/Projects/rst2pdf_py2/rst2pdf/tests/output/test_issue_312_2.pdf


* [INFO] createpdf.py:1572 Importing extension module 'vectorpdf'
* [INFO] languages.py:39 Language 'en_US' not supported by Docutils, using 'en' instead.
* [INFO] styles.py:82 Using stylesheets: 
* [INFO] styles.py:110 FontPath:['/home/david/Projects/rst2pdf_py2/rst2pdf/fonts', '.']
* [INFO] styles.py:111 StylePath:['/home/david/Projects/rst2pdf_py2/rst2pdf/styles', '/home/david/.rst2pdf/styles', '.']
* [INFO] languages.py:39 Language 'en_US' not supported by Docutils, using 'en' instead.
* [ERROR] image.py:357 The image (/home/david/Projects/rst2pdf_py2/rst2pdf/tests/input/images/tall_image.png, near line UNKNOWN in file UNKNOWN) is broken or in an unknown format
* [INFO] createpdf.py:651 Starting build
* [INFO] createpdf.py:1112 Page 1 [1]

Program /home/david/Projects/rst2pdf_py2/bin/rst2pdf exit code: PASS (0)   elapsed time: 00.2 seconds

Validity of file test_issue_312_2.pdf checksum 'ed1cdc396cdab35803e0f7a09dfc2e4f' is unknown.
